locust_commands:
  # Target host
  host: www.ydevbox.sf.com
  # Number of load test users
  users: 3
  # Ramping rate of users per sec.
  rampup: 1
  # Test duration Ex:10s, 5m, 1h, 1h30m20s
  runtime: 1m
  # Time limit to wait until all active users to do exit operations such as log-out.
  rampdown:
  # simply load test shape class that has different user and spawn_rate at different stages
  # All the above attributes will be ignored if any stages involved below
  stages:
    stage1:
#      When this many seconds pass the test is advanced to the next stage
#      duration: 30
##       Total user count
#      users: 2
##       Number of users to start/stop per second
#      spawn_rate: 1
#    stage2:
#      duration: 20
#      users: 5
#      spawn_rate: 1
#    stage3:
#      duration: 30
#      users: 3
#      spawn_rate: 1
user_input:
  # Data source path from where APIs data to read
  api_data: ./input_csv/getPutPost.csv
  # Appliction under test's name for reporting purpose
  app_name: demo_on_0825
  # Run load test post locust script generated
  start_test: False
  # Set the locust html report location
  html_report_location: .
  # Set the locust test script location
  locust_file_location: ./locust_file
  # Test user's authetincation type, for non-salesforce provide value as non-salesforce
  user_auth_type: non-salesforce
  # Test user's test data like login details.
  test_data:
    source: ./input_csv/sf.csv
    reuse_on_eof: True

reporting:
  # Set the splunk endpoint to push the output logs
  splunk_endpoint:
  # Set the splunk endpoint auth key
  splunk_auth_key:
  # Location of the splunk authoring certificate
  splunk_cert:

